-- Update ratio fields in income_statements to have appropriate precision
ALTER TABLE income_statements
ALTER COLUMN gross_profit_ratio TYPE numeric(20,6),
ALTER COLUMN ebitda_ratio TYPE numeric(20,6),
ALTER COLUMN operating_income_ratio TYPE numeric(20,6),
ALTER COLUMN income_before_tax_ratio TYPE numeric(20,6),
ALTER COLUMN net_income_ratio TYPE numeric(20,6);

-- Update numeric fields to have consistent precision
ALTER TABLE income_statements
ALTER COLUMN revenue TYPE numeric(20,2),
ALTER COLUMN cost_of_revenue TYPE numeric(20,2),
ALTER COLUMN gross_profit TYPE numeric(20,2),
ALTER COLUMN research_and_development_expenses TYPE numeric(20,2),
ALTER COLUMN general_and_administrative_expenses TYPE numeric(20,2),
ALTER COLUMN selling_and_marketing_expenses TYPE numeric(20,2),
ALTER COLUMN selling_general_and_administrative_expenses TYPE numeric(20,2),
ALTER COLUMN other_expenses TYPE numeric(20,2),
ALTER COLUMN operating_expenses TYPE numeric(20,2),
ALTER COLUMN cost_and_expenses TYPE numeric(20,2),
ALTER COLUMN interest_income TYPE numeric(20,2),
ALTER COLUMN interest_expense TYPE numeric(20,2),
ALTER COLUMN depreciation_and_amortization TYPE numeric(20,2),
ALTER COLUMN ebitda TYPE numeric(20,2),
ALTER COLUMN operating_income TYPE numeric(20,2),
ALTER COLUMN total_other_income_expenses_net TYPE numeric(20,2),
ALTER COLUMN income_before_tax TYPE numeric(20,2),
ALTER COLUMN income_tax_expense TYPE numeric(20,2),
ALTER COLUMN net_income TYPE numeric(20,2),
ALTER COLUMN eps TYPE numeric(20,6),
ALTER COLUMN eps_diluted TYPE numeric(20,6),
ALTER COLUMN weighted_average_shs_out TYPE numeric(20,2),
ALTER COLUMN weighted_average_shs_out_dil TYPE numeric(20,2);

-- Update ratio fields in balance_sheets to have appropriate precision
ALTER TABLE balance_sheets
ALTER COLUMN cash_and_cash_equivalents TYPE numeric(20,2),
ALTER COLUMN short_term_investments TYPE numeric(20,2),
ALTER COLUMN cash_and_short_term_investments TYPE numeric(20,2),
ALTER COLUMN net_receivables TYPE numeric(20,2),
ALTER COLUMN inventory TYPE numeric(20,2),
ALTER COLUMN other_current_assets TYPE numeric(20,2),
ALTER COLUMN total_current_assets TYPE numeric(20,2),
ALTER COLUMN property_plant_equipment_net TYPE numeric(20,2),
ALTER COLUMN goodwill TYPE numeric(20,2),
ALTER COLUMN intangible_assets TYPE numeric(20,2),
ALTER COLUMN goodwill_and_intangible_assets TYPE numeric(20,2),
ALTER COLUMN long_term_investments TYPE numeric(20,2),
ALTER COLUMN tax_assets TYPE numeric(20,2),
ALTER COLUMN other_non_current_assets TYPE numeric(20,2),
ALTER COLUMN total_non_current_assets TYPE numeric(20,2),
ALTER COLUMN other_assets TYPE numeric(20,2),
ALTER COLUMN total_assets TYPE numeric(20,2),
ALTER COLUMN account_payables TYPE numeric(20,2),
ALTER COLUMN short_term_debt TYPE numeric(20,2),
ALTER COLUMN tax_payables TYPE numeric(20,2),
ALTER COLUMN deferred_revenue TYPE numeric(20,2),
ALTER COLUMN other_current_liabilities TYPE numeric(20,2),
ALTER COLUMN total_current_liabilities TYPE numeric(20,2),
ALTER COLUMN long_term_debt TYPE numeric(20,2),
ALTER COLUMN deferred_revenue_non_current TYPE numeric(20,2),
ALTER COLUMN deferred_tax_liabilities_non_current TYPE numeric(20,2),
ALTER COLUMN other_non_current_liabilities TYPE numeric(20,2),
ALTER COLUMN total_non_current_liabilities TYPE numeric(20,2),
ALTER COLUMN other_liabilities TYPE numeric(20,2),
ALTER COLUMN capital_lease_obligations TYPE numeric(20,2),
ALTER COLUMN total_liabilities TYPE numeric(20,2),
ALTER COLUMN preferred_stock TYPE numeric(20,2),
ALTER COLUMN common_stock TYPE numeric(20,2),
ALTER COLUMN retained_earnings TYPE numeric(20,2),
ALTER COLUMN accumulated_other_comprehensive_income_loss TYPE numeric(20,2),
ALTER COLUMN other_total_stockholders_equity TYPE numeric(20,2),
ALTER COLUMN total_stockholders_equity TYPE numeric(20,2),
ALTER COLUMN total_equity TYPE numeric(20,2),
ALTER COLUMN total_liabilities_and_stockholders_equity TYPE numeric(20,2),
ALTER COLUMN minority_interest TYPE numeric(20,2),
ALTER COLUMN total_liabilities_and_total_equity TYPE numeric(20,2),
ALTER COLUMN total_investments TYPE numeric(20,2),
ALTER COLUMN total_debt TYPE numeric(20,2),
ALTER COLUMN net_debt TYPE numeric(20,2);

-- Update ratio fields in cash_flow_statements to have appropriate precision
ALTER TABLE cash_flow_statements
ALTER COLUMN net_income TYPE numeric(20,2),
ALTER COLUMN depreciation_and_amortization TYPE numeric(20,2),
ALTER COLUMN deferred_income_tax TYPE numeric(20,2),
ALTER COLUMN stock_based_compensation TYPE numeric(20,2),
ALTER COLUMN change_in_working_capital TYPE numeric(20,2),
ALTER COLUMN accounts_receivables TYPE numeric(20,2),
ALTER COLUMN inventory TYPE numeric(20,2),
ALTER COLUMN accounts_payables TYPE numeric(20,2),
ALTER COLUMN other_working_capital TYPE numeric(20,2),
ALTER COLUMN other_non_cash_items TYPE numeric(20,2),
ALTER COLUMN net_cash_provided_by_operating_activities TYPE numeric(20,2),
ALTER COLUMN investments_in_property_plant_and_equipment TYPE numeric(20,2),
ALTER COLUMN acquisitions_net TYPE numeric(20,2),
ALTER COLUMN purchases_of_investments TYPE numeric(20,2),
ALTER COLUMN sales_maturities_of_investments TYPE numeric(20,2),
ALTER COLUMN other_investing_activities TYPE numeric(20,2),
ALTER COLUMN net_cash_used_for_investing_activities TYPE numeric(20,2),
ALTER COLUMN debt_repayment TYPE numeric(20,2),
ALTER COLUMN common_stock_issued TYPE numeric(20,2),
ALTER COLUMN common_stock_repurchased TYPE numeric(20,2),
ALTER COLUMN dividends_paid TYPE numeric(20,2),
ALTER COLUMN other_financing_activities TYPE numeric(20,2),
ALTER COLUMN net_cash_used_provided_by_financing_activities TYPE numeric(20,2),
ALTER COLUMN effect_of_forex_changes_on_cash TYPE numeric(20,2),
ALTER COLUMN net_change_in_cash TYPE numeric(20,2),
ALTER COLUMN cash_at_end_of_period TYPE numeric(20,2),
ALTER COLUMN cash_at_beginning_of_period TYPE numeric(20,2),
ALTER COLUMN operating_cash_flow TYPE numeric(20,2),
ALTER COLUMN capital_expenditure TYPE numeric(20,2),
ALTER COLUMN free_cash_flow TYPE numeric(20,2);
