-- Create revenue_geo_segments table
CREATE TABLE IF NOT EXISTS revenue_geo_segments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol TEXT NOT NULL,
    date DATE NOT NULL,
    reported_currency TEXT NOT NULL,
    period TEXT NOT NULL,
    segments JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (symbol) REFERENCES stock_metadata(symbol)
);

-- Create unique constraint
CREATE UNIQUE INDEX revenue_geo_segments_symbol_date_period_key ON revenue_geo_segments USING btree (symbol, date, period);

-- Create indexes matching revenue_segments
CREATE INDEX idx_revenue_geo_segments_symbol ON revenue_geo_segments USING btree (symbol);
CREATE INDEX idx_revenue_geo_segments_symbol_period ON revenue_geo_segments USING btree (symbol, period);

-- Enable RLS
ALTER TABLE revenue_geo_segments ENABLE ROW LEVEL SECURITY;

-- Add RLS policies matching revenue_segments
CREATE POLICY "Enable read access for authenticated users"
    ON revenue_geo_segments
    FOR SELECT
    TO authenticated
    USING (true);

CREATE POLICY "Enable all operations for service role"
    ON revenue_geo_segments
    FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

-- Grant necessary permissions
GRANT SELECT ON revenue_geo_segments TO authenticated;
GRANT ALL ON revenue_geo_segments TO service_role;
GRANT USAGE, SELECT ON SEQUENCE revenue_geo_segments_id_seq TO service_role;
