name: CI

on:
  push:
  pull_request:

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: "sqlite:///./test.db"
      SECRET_KEY: "thisisasecretkeyforcitesting"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
      - name: Run backend tests
        run: |
          cd backend
          pytest -v --import-mode=importlib
      - name: Run backend linting
        run: |
          flake8 backend
      - name: Run backend type checking
        run: |
          mypy backend

  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
      - name: Clear npm cache
        run: |
          cd frontend
          npm cache clean --force
      - name: Install dependencies
        run: |
          cd frontend
          npm ci
      - name: Run frontend tests
        run: |
          cd frontend
          npm test -- --passWithNoTests
      - name: Run frontend linting
        run: |
          cd frontend
          npm run lint
      - name: Run frontend type checking
        run: |
          cd frontend
          npm run type-check
