name: Python Tests

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11.3]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0 libopengl0 libegl1-mesa libgl1-mesa-glx x11-utils
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Debug environment
        run: |
          python -c "import sys; print(sys.version)"
          python -c "from PySide6 import __version__; print(f'PySide6 version: {__version__}')"
          python -c "from PySide6.QtCore import QLibraryInfo; print(f'Qt version: {QLibraryInfo.version().toString()}')"
          echo "DISPLAY: $DISPLAY"
          echo "QT_QPA_PLATFORM: $QT_QPA_PLATFORM"
      - name: Run non-GUI tests
        run: |
          pytest -v tests/database
      - name: Run GUI tests with debug info
        run: |
          export QT_DEBUG_PLUGINS=1
          export DISPLAY=:99
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          sleep 3
          xvfb-run --auto-servernum pytest -v tests/ui tests/test_main.py
